feat: apply local UI library
penumbra-zone/dex-explorer pull request #114
Opened 2024-10-28 08:15 UTC by VanishMax

This PR inserts the UI package (`src` directory) into the DEX to unblock faster local development.

2024-10-28 08:18 UTC, VanishMax commented on tsconfig.json
> +      "@penumbra-zone/ui/*": ["./src/shared/ui/*"]
this allows importing `@penumbra-zone/ui/Component` from anywhere in the DEX code

2024-10-28 08:18 UTC, VanishMax commented on package.json
> -    "@babel/core": "^7.25.2",
- removed legacy dependencies
- updated existing dependencies
- added many libraries needed to support the UI package

2024-10-28 11:10 UTC, VanishMax commented on package.json
> +    "@storybook/react-webpack5": "^8.3.6",
different Storybook setup comparing to the Web repo – relies on webpack instead of Vite

2024-10-29 02:55 UTC, TalDerei requested changes
proposing closing in favor of https://github.com/penumbra-zone/dex-explorer/issues/115

2024-10-29 09:37 UTC, VanishMax commented
@TalDerei https://github.com/penumbra-zone/dex-explorer/pull/116

2024-10-30 07:48 UTC, closed without merging